### ISSUE TITLE
Tags para Pedido Agendado "Sheduled Order"

### ISSUE THREAD

**Issue by sfhera** [Abrasel-Nacional/Open-Delivery-Beta-Test#17]
Não encontramos na API nenhum indicação para pedido agendado, a tag "orderTiming": "INSTANT", que identifica se o pedido é para entrega imediata ou futura, porem nada indicando, caso seja agendado, qual data e hora deve ser entregue.

Sei que talvez não seja foco nesse primeiro momento, mas nós temos agendamento, então teremos que criar algo nosso para quebrar o galho, porém isso pode ser ruim, porque depois nossos parceiros terão que mudar.

Segue modelo do iFood:

"schedule": {
    "deliveryDateTimeStart": "2021-09-17T15:22:28.967Z",
    "deliveryDateTimeEnd": "2021-09-17T15:22:28.967Z"
  }

Eu acho interessante pensar nisso, pois é bem importante.

**Comment by gui-camargo** [comment]
Olá @sfhera.

A pedido agendado bem como a edição de pedidos, não está previsto para a versão de lançamento da API, mas já está no roadmap para as próximas versões, a serem discutidas logo após o lançamento.

Obrigado pela sugestão.

**Comment by gui-camargo** [comment]
A issue será fechada por falta de novas informações.

**Comment by gui-camargo** [comment]
A evolução de pedidos agendados está sendo tratada na issue #89.

@filipesarturi sobre sua sugestão, vamos colocar no nosso backlog, para uma discussão de evolução para as próximas versões.
