### ISSUE TITLE
[DeliveryVip] Confirmação do pedido

### ISSUE THREAD

**Issue by danieldocki** [Abrasel-Nacional/Open-Delivery-Beta-Test#92]
Quando acontece a confirmação do pedido no

`POST /confirm`

e por algum engano é enviado novamente esse request

`POST /confirm`

Temos que aceitar essa confirmação ou retornar um erro?

No meu caso estou retornando que não aceitei o evento porque já foi confirmado o pedido.

**Comment by gui-camargo** [comment]
Olá @danieldocki 
Como o @filipesarturi falou, fica a cargo das partes o tratamento de duplicidades. Mas podemos conversar no comite se podemos adotar alguma recomendação como padrão, ou até colocar algum código mais especifico, como o HTTP 409 Conflict por exemplo.

**Comment by danieldocki** [comment]
Hoje estou retornando 422 quando um pedido já foi confirmado.

**Comment by gui-camargo** [comment]
Olá @danieldocki 

Adicionamos o HTTP code 422 nos endpoints dos eventos do pedido.

Já disponível na versão 1.0.1.
